// Edge Case Scenarios Configuration
// 32 FMEA edge cases for Physical AI LEGO Loader Simulator
// Each scenario defines environment parameters for the parameterized simulator

export const CATEGORIES = {
  A: { name: '환경 위험', nameEn: 'Environmental Hazards', color: '#4A90D9' },
  B: { name: '안전 위협', nameEn: 'Safety-Critical Hazards', color: '#E74C3C' },
  C: { name: '수거 조작', nameEn: 'Manipulation Edge Cases', color: '#F39C12' },
  D: { name: '탐색/경로', nameEn: 'Navigation Edge Cases', color: '#27AE60' },
  E: { name: '동적 환경', nameEn: 'Dynamic Environment', color: '#8E44AD' },
  F: { name: '로봇 내부', nameEn: 'Robot Internal Failures', color: '#7F8C8D' },
};

export const SCENARIOS = [
  // ============================================
  // Category A: Environmental Hazards (7)
  // ============================================
  {
    id: 'FM-A01',
    name: '바닥색 동일 레고',
    nameEn: 'Floor-colored Legos',
    category: 'A',
    tier: 1,
    sps: 21.0,
    severity: 7, occurrence: 6, detection: 2,
    description: '레고가 바닥과 동일한 색상이라 감지 실패',
    descriptionEn: 'Legos match floor color, causing detection failure',
    failureMode: '무한 스캔 루프, 에피소드 타임아웃',
    implementable: true,
    implementationType: 'A', // parameter-only

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 15, colors: [0xDEB887, 0xC8A882, 0xD4C4A0], distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },
  {
    id: 'FM-A02',
    name: '강한 방향성 조명/그림자',
    nameEn: 'Harsh directional lighting',
    category: 'A',
    tier: 2,
    sps: 13.3,
    severity: 5, occurrence: 8, detection: 3,
    description: '강한 그림자가 레고를 가리거나 유령 물체 생성',
    descriptionEn: 'Strong shadows hide legos or create ghost objects',
    failureMode: '탐지 실패 또는 오탐지',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.2, directionalIntensity: 3.0, directionalPosition: [4, 12, 3], shadowIntensity: 0.9 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },
  {
    id: 'FM-A03',
    name: '어두운 환경 / 저조도',
    nameEn: 'Dark environment / low light',
    category: 'A',
    tier: 1,
    sps: 24.0,
    severity: 6, occurrence: 8, detection: 2,
    description: '조도 부족으로 전체적인 인지 성능 저하',
    descriptionEn: 'Low light causes overall perception degradation',
    failureMode: '수거율 전반 하락 (50% 이하)',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.1, directionalIntensity: 0.3, directionalPosition: [8, 15, 10], shadowIntensity: 0.3, toneMappingExposure: 0.6 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },
  {
    id: 'FM-A04',
    name: '바닥 경사 / 문턱',
    nameEn: 'Floor slope / threshold',
    category: 'A',
    tier: 2,
    sps: 6.0,
    severity: 5, occurrence: 6, detection: 5,
    description: '경사면에서 레고가 미끄러지거나 로더 접근각 오류',
    descriptionEn: 'Legos slide on slopes, loader approach angle errors',
    failureMode: '퍼담기 실패, 반복 재시도',
    implementable: true,
    implementationType: 'B', // small code addition

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    floorSlope: { angle: 3, axis: 'z' },
  },
  {
    id: 'FM-A05',
    name: '좁은 공간 (가구 사이 틈)',
    nameEn: 'Narrow space between furniture',
    category: 'A',
    tier: 2,
    sps: 14.0,
    severity: 6, occurrence: 7, detection: 3,
    description: '로더가 가구 사이에 끼이거나 레고에 접근 불가',
    descriptionEn: 'Loader stuck between furniture or cannot reach legos',
    failureMode: '접근 불가 레고 존재',
    implementable: true,
    implementationType: 'B',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 15, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: {
      density: 'high',
      extras: [
        { type: 'table', position: [2, 0, -2], size: [2, 1.2, 1.5] },
        { type: 'table', position: [-2, 0, 3], size: [2.5, 1.2, 1.8] },
        { type: 'shelf', position: [5, 0, 0], size: [0.8, 2, 3] },
      ],
    },
    dynamic: {},
  },
  {
    id: 'FM-A06',
    name: '반사 바닥 (광택 타일)',
    nameEn: 'Reflective floor (glossy tiles)',
    category: 'A',
    tier: 2,
    sps: 6.7,
    severity: 4, occurrence: 5, detection: 3,
    description: '반사로 인한 깊이 추정 오류, 미끄러운 바닥',
    descriptionEn: 'Reflection causes depth errors, slippery surface',
    failureMode: '접근 각도 오차, 운반 중 레고 낙하',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xE8DCC8, floorRoughness: 0.05, floorMetalness: 0.5 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },
  {
    id: 'FM-A07',
    name: '배경 잡동사니 (비레고 물체)',
    nameEn: 'Background clutter (non-lego)',
    category: 'A',
    tier: 2,
    sps: 15.0,
    severity: 5, occurrence: 9, detection: 3,
    description: '비레고 물체를 레고로 오인 또는 레고를 비레고로 오인',
    descriptionEn: 'Non-lego objects misclassified as legos or vice versa',
    failureMode: '불필요한 수거 시도, 실제 레고 누락',
    implementable: true,
    implementationType: 'B',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 15, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    distractors: { count: 12, types: ['sphere', 'cylinder', 'coin', 'battery'] },
  },

  // ============================================
  // Category B: Safety-Critical Hazards (6)
  // ============================================
  {
    id: 'FM-B01',
    name: '절벽/계단 가장자리',
    nameEn: 'Cliff/stair edge',
    category: 'B',
    tier: 2,
    sps: 6.75,
    severity: 9, occurrence: 3, detection: 4,
    description: '절벽 가장자리를 인식하지 못하고 추락',
    descriptionEn: 'Falls off cliff edge without detection',
    failureMode: '치명적 하드웨어 손상',
    implementable: false,
    implementationType: 'C',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    expectedBehavior: '가장자리 1m 전 정지 (emergency_stop)',
  },
  {
    id: 'FM-B02',
    name: '바닥 함몰 / 구멍',
    nameEn: 'Floor hole / sinkhole',
    category: 'B',
    tier: 3,
    sps: 4.0,
    severity: 8, occurrence: 2, detection: 4,
    description: '바닥 구멍을 감지하지 못하고 진입',
    descriptionEn: 'Enters floor hole without detection',
    failureMode: '로봇 기울어짐, 물리 불안정',
    implementable: false,
    implementationType: 'C',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    expectedBehavior: '구멍 주변 0.5m 회피 영역 설정 (avoid_zone)',
  },
  {
    id: 'FM-B03',
    name: '동적 장애물 — 애완동물',
    nameEn: 'Dynamic obstacle — Pet',
    category: 'B',
    tier: 2,
    sps: 11.25,
    severity: 9, occurrence: 5, detection: 4,
    description: '이동 중인 동물과 충돌, 또는 동물이 레고를 물고 감',
    descriptionEn: 'Collision with moving pet or pet takes lego',
    failureMode: '안전 사고, 수거 대상 소실',
    implementable: false,
    implementationType: 'C',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    expectedBehavior: '2m 이내 접근 시 정지, 멀어지면 재개 (pause_and_wait)',
  },
  {
    id: 'FM-B04',
    name: '동적 장애물 — 아이',
    nameEn: 'Dynamic obstacle — Child',
    category: 'B',
    tier: 2,
    sps: 10.0,
    severity: 10, occurrence: 5, detection: 5,
    description: '아이와 충돌, 아이가 정리한 레고를 다시 흩뜨림',
    descriptionEn: 'Collision with child, child scatters collected legos',
    failureMode: '인명 안전 위협 (최고 심각도)',
    implementable: false,
    implementationType: 'C',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    expectedBehavior: '3m 이내 즉시 완전 정지, 5m 이상 멀어질 때까지 대기 (full_stop)',
  },
  {
    id: 'FM-B05',
    name: '금지 물체 인접 (깨지기 쉬운 것)',
    nameEn: 'Fragile object nearby',
    category: 'B',
    tier: 2,
    sps: 14.0,
    severity: 7, occurrence: 6, detection: 3,
    description: '레고 수거 시 인접한 유리컵/전자기기 접촉/파손',
    descriptionEn: 'Contacts fragile objects while collecting legos',
    failureMode: '재산 손실, 위험 파편 생성',
    implementable: true,
    implementationType: 'B',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 15, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    forbiddenObjects: [
      { type: 'glass', position: [2, 0, 1], safetyRadius: 0.5 },
      { type: 'vase', position: [-1, 0, 3], safetyRadius: 0.4 },
      { type: 'electronics', position: [4, 0, -3], safetyRadius: 0.6 },
    ],
  },
  {
    id: 'FM-B06',
    name: '경사로에서 고속 하강',
    nameEn: 'High-speed ramp descent',
    category: 'B',
    tier: 3,
    sps: 4.2,
    severity: 7, occurrence: 3, detection: 5,
    description: '경사면을 고속으로 내려가며 제어 상실',
    descriptionEn: 'Loses control descending ramp at high speed',
    failureMode: '충돌, 레고 비산, 물리 불안정',
    implementable: false,
    implementationType: 'C',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    expectedBehavior: '경사면 감지 시 속도 제한',
  },

  // ============================================
  // Category C: Manipulation Edge Cases (8)
  // ============================================
  {
    id: 'FM-C01',
    name: '벽/가구 코너에 밀착된 레고',
    nameEn: 'Wall/corner-adjacent legos',
    category: 'C',
    tier: 1,
    sps: 20.0,
    severity: 5, occurrence: 8, detection: 2,
    description: '정면 접근 불가, 버킷이 벽에 부딪힘',
    descriptionEn: 'Cannot approach head-on, bucket hits wall',
    failureMode: '수거 실패, 반복 충돌',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'wall_adjacent', wallRatio: 0.4, types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },
  {
    id: 'FM-C02',
    name: '레고 밀집 클러스터',
    nameEn: 'Dense lego cluster',
    category: 'C',
    tier: 2,
    sps: 17.5,
    severity: 5, occurrence: 7, detection: 2,
    description: '한 번에 여러 개 퍼담으려다 흘림, 경로 혼선',
    descriptionEn: 'Multiple pickup attempts cause spillage',
    failureMode: '수거 효율 급락, 반복 실패',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 25, colors: null, distribution: 'clustered', clusterCount: 2, types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },
  {
    id: 'FM-C03',
    name: '운반 중 급회전 낙하',
    nameEn: 'Sharp turn during transport',
    category: 'C',
    tier: 2,
    sps: 16.0,
    severity: 4, occurrence: 8, detection: 2,
    description: '급격한 steering 변화로 버킷의 레고가 떨어짐',
    descriptionEn: 'Sharp steering causes lego to fall from bucket',
    failureMode: '재수거 필요, 비효율 경로',
    implementable: true,
    implementationType: 'B',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    obstacles: [
      { type: 'box', position: [0, 0, -2], size: [1.5, 0.8, 1.5] },
      { type: 'box', position: [-3, 0, 1], size: [1, 0.6, 1] },
    ],
  },
  {
    id: 'FM-C04',
    name: '초대형 레고 (버킷 용량 초과)',
    nameEn: 'Oversized legos',
    category: 'C',
    tier: 2,
    sps: 10.0,
    severity: 5, occurrence: 4, detection: 2,
    description: '레고가 너무 커서 버킷에 안 들어감',
    descriptionEn: 'Legos too large for bucket capacity',
    failureMode: '해당 레고 수거 불가',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 15, colors: null, distribution: 'random', types: { xlarge: 1.0 } },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },
  {
    id: 'FM-C05',
    name: '부분 가림 레고',
    nameEn: 'Partially occluded legos',
    category: 'C',
    tier: 2,
    sps: 11.7,
    severity: 5, occurrence: 7, detection: 3,
    description: '부분 가림으로 인해 위치 추정 오류',
    descriptionEn: 'Partial occlusion causes position estimation errors',
    failureMode: '버킷 빗나감, 방해물과 충돌',
    implementable: true,
    implementationType: 'B',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 15, colors: null, distribution: 'under_furniture', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: {
      density: 'normal',
      extras: [
        { type: 'table', position: [3, 0, 2], size: [2, 1.0, 1.5] },
      ],
    },
    dynamic: {},
  },
  {
    id: 'FM-C06',
    name: '초소형 레고 (1x1 단일 블록)',
    nameEn: 'Tiny legos (1x1 bricks)',
    category: 'C',
    tier: 2,
    sps: 10.5,
    severity: 3, occurrence: 7, detection: 2,
    description: '너무 작아 감지 실패 또는 버킷에 안 걸림',
    descriptionEn: 'Too small to detect or catch in bucket',
    failureMode: '수거 누락',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 25, colors: null, distribution: 'random', types: { tiny: 1.0 } },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },
  {
    id: 'FM-C07',
    name: '바닥에 붙은 레고 (밟혀서 끼임)',
    nameEn: 'Floor-stuck legos',
    category: 'C',
    tier: 2,
    sps: 5.0,
    severity: 4, occurrence: 5, detection: 4,
    description: '레고가 바닥에 강하게 밀착, 버킷으로 분리 불가',
    descriptionEn: 'Legos stuck to floor, cannot be separated by bucket',
    failureMode: '퍼담기 무한 재시도, 타임아웃',
    implementable: true,
    implementationType: 'B',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    stuckLegoRatio: 0.15,
    stuckScoopExtraTime: 1.5,
  },
  {
    id: 'FM-C08',
    name: '수거함이 이미 가득 참',
    nameEn: 'Collection box already full',
    category: 'C',
    tier: 2,
    sps: 5.3,
    severity: 4, occurrence: 4, detection: 3,
    description: '수거함 용량 초과로 투하된 레고가 밖으로 튀어나옴',
    descriptionEn: 'Box overflow causes dumped legos to bounce out',
    failureMode: '재수거 필요, 비효율',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 50, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'small' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },

  // ============================================
  // Category D: Navigation Edge Cases (4)
  // ============================================
  {
    id: 'FM-D01',
    name: '코너 고착 (무한 루프)',
    nameEn: 'Corner trap (infinite loop)',
    category: 'D',
    tier: 2,
    sps: 15.0,
    severity: 6, occurrence: 5, detection: 2,
    description: '오목 코너에서 벗어나지 못하고 왕복 반복',
    descriptionEn: 'Stuck in concave corner, oscillating back and forth',
    failureMode: '에피소드 타임아웃, 수거 0개',
    implementable: true,
    implementationType: 'B',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 15, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: {
      density: 'high',
      extras: [
        { type: 'shelf', position: [5, 0, 5], size: [0.5, 2, 3] },
        { type: 'shelf', position: [6.5, 0, 3.5], size: [3, 2, 0.5] },
      ],
    },
    dynamic: {},
  },
  {
    id: 'FM-D02',
    name: '레고 극도 분산',
    nameEn: 'Extreme lego spread',
    category: 'D',
    tier: 1,
    sps: 24.0,
    severity: 4, occurrence: 6, detection: 1,
    description: '비효율적 경로로 시간 낭비, 타임아웃',
    descriptionEn: 'Inefficient paths waste time, timeout',
    failureMode: '수거율 낮음 (시간 부족)',
    implementable: true,
    implementationType: 'A',

    room: { size: 20, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 30, colors: null, distribution: 'extreme_spread', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },
  {
    id: 'FM-D03',
    name: '로더 시작점 최원거리',
    nameEn: 'Loader at farthest point',
    category: 'D',
    tier: 2,
    sps: 15.0,
    severity: 3, occurrence: 5, detection: 1,
    description: '매 운반마다 장거리 이동, 시간 낭비',
    descriptionEn: 'Long distance transport each cycle',
    failureMode: '수거 효율 저하',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [7, 0, 7] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
  },
  {
    id: 'FM-D04',
    name: '예상외 정적 장애물',
    nameEn: 'Unexpected static obstacles',
    category: 'D',
    tier: 2,
    sps: 7.0,
    severity: 3, occurrence: 7, detection: 3,
    description: '평소 없던 물체가 경로를 막음',
    descriptionEn: 'Unexpected objects block path',
    failureMode: '경로 우회 필요, 시간 지연',
    implementable: true,
    implementationType: 'B',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    obstacles: [
      { type: 'cardboard', position: [0, 0, 0], size: [1.2, 0.8, 0.8] },
      { type: 'shoes', position: [2, 0, -3], size: [0.4, 0.15, 0.3] },
      { type: 'box', position: [-3, 0, 2], size: [0.6, 0.4, 0.5] },
    ],
  },

  // ============================================
  // Category E: Dynamic Environment Changes (4)
  // ============================================
  {
    id: 'FM-E01',
    name: '작업 중 조명 변화',
    nameEn: 'Lighting change during operation',
    category: 'E',
    tier: 2,
    sps: 7.5,
    severity: 6, occurrence: 5, detection: 4,
    description: '에피소드 중간에 밝기가 급변, 인지 모델 혼란',
    descriptionEn: 'Brightness changes mid-episode, confusing perception',
    failureMode: '중간부터 감지율 급락',
    implementable: true,
    implementationType: 'B',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {
      lightingTransition: {
        fromAmbient: 0.5,
        fromDirectional: 1.8,
        toAmbient: 0.08,
        toDirectional: 0.15,
        atProgress: 0.4,
        durationSec: 8,
      },
    },
  },
  {
    id: 'FM-E02',
    name: '사람이 레고를 밟아 위치 변경',
    nameEn: 'Lego displaced by person',
    category: 'E',
    tier: 3,
    sps: 4.8,
    severity: 4, occurrence: 6, detection: 5,
    description: '이미 감지한 레고가 사라지거나 위치 이동',
    descriptionEn: 'Previously detected lego disappears or moves',
    failureMode: '유령 타겟 추적, 빈 곳에서 퍼담기 시도',
    implementable: false,
    implementationType: 'C',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    expectedBehavior: '타겟 소실 시 재스캔',
  },
  {
    id: 'FM-E03',
    name: '문이 열리며 새로운 영역 노출',
    nameEn: 'Door opens, exposing new area',
    category: 'E',
    tier: 3,
    sps: 1.5,
    severity: 3, occurrence: 3, detection: 6,
    description: '탐색 범위가 갑자기 확장, 기존 경로 무효화',
    descriptionEn: 'Exploration area suddenly expands',
    failureMode: '경로 재계획 필요, 시간 지연',
    implementable: false,
    implementationType: 'C',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    expectedBehavior: '새 영역 레고 포함하여 경로 재계획',
  },
  {
    id: 'FM-E04',
    name: '바닥 함몰 (갑자기 꺼짐)',
    nameEn: 'Sudden floor collapse',
    category: 'E',
    tier: 3,
    sps: 1.8,
    severity: 9, occurrence: 1, detection: 5,
    description: '주행 중 바닥 일부가 무너짐',
    descriptionEn: 'Floor partially collapses during operation',
    failureMode: '치명적 손상, 에피소드 즉시 종료',
    implementable: false,
    implementationType: 'C',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    expectedBehavior: '의심 지형 회피 (avoid_suspicious_terrain)',
  },

  // ============================================
  // Category F: Robot Internal Failures (3)
  // ============================================
  {
    id: 'FM-F01',
    name: '버킷-바닥 끼임 (물리 진동)',
    nameEn: 'Bucket-ground jam (physics vibration)',
    category: 'F',
    tier: 2,
    sps: 15.0,
    severity: 6, occurrence: 5, detection: 2,
    description: '버킷이 바닥에 끼여 진동 발생, 물리 불안정',
    descriptionEn: 'Bucket jams into floor causing physics instability',
    failureMode: '에피소드 중단, 학습 데이터 오염',
    implementable: true,
    implementationType: 'B',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    bucketVibration: { amplitude: 0.03, frequency: 8 },
  },
  {
    id: 'FM-F02',
    name: '동일 레고 반복 타겟팅',
    nameEn: 'Ghost target re-targeting',
    category: 'F',
    tier: 2,
    sps: 8.0,
    severity: 4, occurrence: 4, detection: 2,
    description: '수거 완료된 레고 위치를 재방문',
    descriptionEn: 'Revisits position of already collected lego',
    failureMode: '시간 낭비, 비효율',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    ghostTargetDelay: 3,
  },
  {
    id: 'FM-F03',
    name: '센서 노이즈 (카메라 흔들림)',
    nameEn: 'Sensor noise (camera shake)',
    category: 'F',
    tier: 2,
    sps: 8.0,
    severity: 4, occurrence: 6, detection: 3,
    description: '위치 추정에 노이즈가 섞여 접근 각도 오류',
    descriptionEn: 'Position noise causes approach angle errors',
    failureMode: '퍼담기 빗나감, 재시도 필요',
    implementable: true,
    implementationType: 'A',

    room: { size: 16, floorColor: 0xDEB887, floorRoughness: 0.8, floorMetalness: 0.0 },
    lighting: { ambientIntensity: 0.5, directionalIntensity: 1.8, directionalPosition: [8, 15, 10], shadowIntensity: 0.5 },
    legos: { count: 20, colors: null, distribution: 'random', types: {} },
    loader: { startPosition: [4, 0, 4] },
    box: { position: [-6, 0, -6], size: 'normal' },
    furniture: { density: 'normal', extras: [] },
    dynamic: {},
    sensorNoise: { position: 0.05, rotation: 0.03 },
  },
];

// Helper: get scenario by ID
export function getScenario(id) {
  return SCENARIOS.find(s => s.id === id);
}

// Helper: get scenarios by category
export function getByCategory(cat) {
  return SCENARIOS.filter(s => s.category === cat);
}

// Helper: get scenarios by tier
export function getByTier(tier) {
  return SCENARIOS.filter(s => s.tier === tier);
}

// Helper: get implementable scenarios
export function getImplementable() {
  return SCENARIOS.filter(s => s.implementable);
}

// Helper: get stats
export function getStats() {
  const total = SCENARIOS.length;
  const implementable = SCENARIOS.filter(s => s.implementable).length;
  const tierCounts = { 1: 0, 2: 0, 3: 0 };
  const catCounts = {};
  SCENARIOS.forEach(s => {
    tierCounts[s.tier]++;
    catCounts[s.category] = (catCounts[s.category] || 0) + 1;
  });
  return { total, implementable, notImplementable: total - implementable, tierCounts, catCounts };
}
